### ISSUE TITLE
tektonlog doesn't return the logs of all tasks/pods

### ISSUE THREAD

**Issue by vbehar** [jenkins-x-plugins/jx-pipeline#382]
see this slack thread for the whole context: https://kubernetes.slack.com/archives/C9MBGQJRH/p1621233109180200

the issue is with a pipelinerun with 5 (sequential) taskruns: if you try to get the logs while task 3 is running, the `getRunningBuildLogs` func will only see the first 3 tasks/pods, and so will never return the logs for the 2 other tasks/pods, because they don't exists yet at the beginning of the func when the internal state is constructed.

the fix is to reload the pipelinerun when all pods have been seen, if there are more tasks than pods.

**Comment by serhiykrupka** [comment]
fixed in PR #385
